### ISSUE TITLE
System.Exception: wrong ship position

### ISSUE THREAD

**Issue by madddmax** [madddmax/jackal#42]
Код игры: 8e5d3f93-56cd-4ec2-80c3-29210cfdfe98
Код карты: -1824134380
Размер карты: 11
Номер хода: 714

Server HTTP Code 500

```
System.Exception: wrong ship position
   at Jackal.Core.Board.GetShipLanding(Position pos) in /root/madddmax/jackal/Jackal.Core/Board.cs:line 518
   at Jackal.Core.Board.GetAllTargetsForSubTurn(TilePosition source, Direction prevMove, Team ourTeam) in /root/madddmax/jackal/Jackal.Core/Board.cs:line 422
   at Jackal.Core.Board.GetAllAvailableMoves(GetAllAvaliableMovesTask task, TilePosition source, TilePosition prev) in /root/madddmax/jackal/Jackal.Core/Board.cs:line 191
   at Jackal.Core.Game.GetAvailableMoves(Int32 teamId) in /root/madddmax/jackal/Jackal.Core/Game.cs:line 136
   at Jackal.Core.Game.Turn() in /root/madddmax/jackal/Jackal.Core/Game.cs:line 49
   at JackalWebHost.Controllers.GameController.Turn(String gameName, Nullable`1 turnNum, Nullable`1 pirateId) in /root/madddmax/jackal/JackalWebHost2/Controllers/GameController.cs:line 132
   at JackalWebHost.Controllers.GameController.MakeTurn(TurnGameModel request) in /root/madddmax/jackal/JackalWebHost2/Controllers/GameController.cs:line 111
```

**Comment by grmike** [comment]
![image_2024-08-17_23-31-39](https://github.com/user-attachments/assets/41afbac3-1e4c-41e9-a944-1bc5042e2f02)

**Comment by madddmax** [comment]
Fix
